/* ==========================================================================
   📕 KİTAP SORULARI — "Green TOEFL Structure" Diagnostic Pre-Test (Paper)
   Kitaptan BİREBİR alınmıştır. Doğru cevaplar kitabın skill cevap anahtarı +
   gramer ile doğrulanmıştır. (OCR'ı bozuk olan 1 soru hariç tutuldu.)
   Şema app.js ile uyumlu: mc / err.
   ========================================================================== */
const BOOK = {
  title: "Kitap Pre-Test (Paper)",
  source: "Green TOEFL Structure — Diagnostic Pre-Test",
  questions: [
    // ---- STRUCTURE (1–15): boşluk doldurma ----
    { type:"mc", _skill:1, stem:"In the early 1900s, Eastman ___ inexpensive Brownie box cameras.",
      options:["it developed","it was developed","developed","developing"], answer:2,
      explain:"Özne (Eastman) var, fiil gerekli → 'developed'. (A)(B) fazladan özne, (D) tek başına fiil olamaz." },
    { type:"mc", _skill:2, stem:"___ the discovery of the fossilized remnants of tides in one-billion-year-old rocks.",
      options:["Geological reports","Geologists report","The reports of geologists","Geologists' reports"], answer:1,
      explain:"Cümlenin özne+fiili lazım → 'Geologists report' (S+V). Diğerleri sadece isim öbeği." },
    { type:"mc", _skill:9, stem:"The Brooklyn Bridge ___ took thirteen years to complete.",
      options:["in New York","is in New York","it is in New York","which New York"], answer:0,
      explain:"Asıl fiil 'took' var; araya niteleyici öbek gelir → 'in New York'." },
    { type:"mc", _skill:4, stem:"Genes control all of the physical ___ we inherit.",
      options:["that traits","that are traits","traits that","traits are that"], answer:2,
      explain:"İsim + adjective clause: 'traits that we inherit'." },
    { type:"mc", _skill:5, stem:"Indigo can be extracted from a plant, and then ___ to dye cloth blue.",
      options:["it","using","using it","it can be used"], answer:3,
      explain:"İkinci clause'a özne+fiil lazım → 'it can be used'." },
    { type:"mc", _skill:1, stem:"___ in the United States spends 900 hours per year in class and 1,170 hours in front of the television.",
      options:["The average third-grader","The third grade is average","There are three grades","Three average grades"], answer:0,
      explain:"Tekil fiil 'spends' için tekil özne → 'The average third-grader'." },
    { type:"mc", _skill:7, stem:"Researchers have begun studying what ___ is on human circadian rhythms.",
      options:["it is the effect of light","the light affects","in affecting the light","the effect of light"], answer:3,
      explain:"'what ... is' yapısının öznesi → 'the effect of light'." },
    { type:"mc", _skill:6, stem:"If calcium oxide remains exposed to air, ___ to calcium carbonate.",
      options:["turning","turns","it turns","the turn"], answer:2,
      explain:"İkinci clause'a özne+fiil lazım → 'it turns'." },
    { type:"mc", _skill:5, stem:"Some early batteries used concentrated nitric acid, ___ gave off poisonous fumes.",
      options:["they","then they","but they","but they had"], answer:2,
      explain:"İki clause arası bağlaç+özne → 'but they'." },
    { type:"mc", _skill:3, stem:"The sound produced by an object ___ in a periodic way involves more than the simple sine wave.",
      options:["it vibrates","vibrating","is vibrating","vibrates"], answer:1,
      explain:"Asıl fiil 'involves' var; 'object'i niteleyen participle → 'vibrating'." },
    { type:"mc", _skill:6, stem:"Prior to the discovery of anesthetics in 1846, surgery was done ___ was still conscious.",
      options:["while the patient","the patient felt","during the patient's","while patiently"], answer:0,
      explain:"İkinci clause'a bağlaç+özne lazım → 'while the patient'." },
    { type:"mc", _skill:8, stem:"The drastic decline of the beaver helps to illustrate what ___ to the ecosystems of the North American continent.",
      options:["happening","the happening","has happened","about happening"], answer:2,
      explain:"'what' bağlaç+özne; ardından fiil → 'has happened'." },
    { type:"mc", _skill:4, stem:"The use of shorthand died out in the Middle Ages because of ___ with witchcraft.",
      options:["the association was imagined","associate the imagination","imagine the association","the imagined association"], answer:3,
      explain:"'because of' edatından sonra isim öbeği; past participle sıfatla → 'the imagined association'." },
    { type:"mc", _skill:10, stem:"A yacht is steered with a rudder, ___ the flow of water that passes the hull.",
      options:["which deflecting","deflects","it deflects","which deflects"], answer:3,
      explain:"'rudder'ı niteleyen adjective clause: bağlaç+fiil → 'which deflects'." },
    { type:"mc", _skill:2, stem:"For top speed and sudden acceleration, the accelerator pump feeds additional gasoline from the float chamber into ___ above the venturi tube.",
      options:["the air it flows","the airflow","the air is flowing","the air flows"], answer:1,
      explain:"'into' edatından sonra isim (nesne) gerekir → 'the airflow'." },

    // ---- WRITTEN EXPRESSION (16–40): hatalı altı çizili bölümü bul ----
    { type:"err", _skill:18, answer:"A", correction:"'got' → 'get' (modal 'could' + yalın fiil)",
      explain:"Skill 18: modal + yalın fiil. 'could got' → 'could get'.",
      segments:[{plain:"In 1732, coach travelers could "},{choice:"A",text:"got"},{plain:" from New York "},{choice:"B",text:"to"},{plain:" Philadelphia in "},{choice:"C",text:"about"},{plain:" two "},{choice:"D",text:"days"},{plain:"."}] },
    { type:"err", _skill:12, answer:"B", correction:"'are' → 'is' ('Some of the District' tekil)",
      explain:"Skill 12: 'some of' + tekil isim → tekil fiil.",
      segments:[{plain:"Some of the "},{choice:"A",text:"District"},{plain:" of Columbia "},{choice:"B",text:"are"},{plain:" on "},{choice:"C",text:"low-lying"},{plain:", marshy "},{choice:"D",text:"ground"},{plain:"."}] },
    { type:"err", _skill:24, answer:"C", correction:"'main' → 'mainly' (fiili niteler, zarf)",
      explain:"Skill 24: fiili niteleyen sözcük zarf olmalı.",
      segments:[{plain:"Georgia's "},{choice:"A",text:"economy"},{plain:" is "},{choice:"B",text:"based"},{plain:" "},{choice:"C",text:"main"},{plain:" on "},{choice:"D",text:"agriculture"},{plain:"."}] },
    { type:"err", _skill:22, answer:"C", correction:"'its' → 'it's' (it is)",
      explain:"Skill 22: 'its' iyelik; burada 'it is' gerek → 'it's'.",
      segments:[{plain:"The Paul Revere House was "},{choice:"A",text:"built"},{plain:" in 1676, and "},{choice:"B",text:"today"},{plain:" "},{choice:"C",text:"its"},{plain:" the oldest wooden "},{choice:"D",text:"building"},{plain:" in Boston."}] },
    { type:"err", _skill:1, answer:"B", correction:"'they' atılmalı (fazladan özne)",
      explain:"Skill 1: cümlenin öznesi 'Conifers'; 'they' fazladan öznedir.",
      segments:[{plain:"Conifers such as "},{choice:"A",text:"cedars"},{plain:", firs, and pines "},{choice:"B",text:"they"},{plain:" "},{choice:"C",text:"bear"},{plain:" their seeds in "},{choice:"D",text:"cones"},{plain:"."}] },
    { type:"err", _skill:2, answer:"D", correction:"'build' → 'building' (edatın nesnesi isim olmalı)",
      explain:"'on top of a ___' → isim gerekir: 'building'.",
      segments:[{plain:"A "},{choice:"A",text:"dome"},{plain:" is a semispherical "},{choice:"B",text:"structure"},{plain:" on "},{choice:"C",text:"top of"},{plain:" a "},{choice:"D",text:"build"},{plain:"."}] },
    { type:"err", _skill:20, answer:"B", correction:"'hour' → 'hours' ('a few' + çoğul)",
      explain:"Skill 20: 'a few' sayılabilen çoğul ister.",
      segments:[{plain:"Succulents "},{choice:"A",text:"suck up"},{plain:" water in just a few "},{choice:"B",text:"hour"},{plain:", but they can "},{choice:"C",text:"store"},{plain:" it in their "},{choice:"D",text:"stems"},{plain:" for months."}] },
    { type:"err", _skill:14, answer:"C", correction:"'thinnest' → 'thin' (paralellik: tall but thin)",
      explain:"Skill 14: 'tall but ___' paralel olmalı → 'thin'.",
      segments:[{plain:"Flying buttresses "},{choice:"A",text:"enabled"},{plain:" builders to "},{choice:"B",text:"put up"},{plain:" tall but "},{choice:"C",text:"thinnest"},{plain:" stone "},{choice:"D",text:"walls"},{plain:"."}] },
    { type:"err", _skill:21, answer:"C", correction:"'they' → 'them' (fiilin nesnesi)",
      explain:"Skill 21: 'record ___' fiilin nesnesi → 'them'.",
      segments:[{plain:"Weather forecasters "},{choice:"A",text:"monitor"},{plain:" barometric pressures and "},{choice:"B",text:"record"},{plain:" "},{choice:"C",text:"they"},{plain:" on charts as "},{choice:"D",text:"isobars"},{plain:"."}] },
    { type:"err", _skill:11, answer:"B", correction:"'varies' → 'vary' (özne 'forms' çoğul)",
      explain:"Skill 11: asıl özne 'forms' (çoğul); araya 'of a word' girmiş.",
      segments:[{plain:"In many languages, the "},{choice:"A",text:"forms"},{plain:" of a word "},{choice:"B",text:"varies"},{plain:" to "},{choice:"C",text:"express"},{plain:" such contrasts as number, gender, and "},{choice:"D",text:"tense"},{plain:"."}] },
    { type:"err", _skill:16, answer:"B", correction:"'provides' → 'provided' (has + V3)",
      explain:"Skill 16: have/has + past participle → 'provided'.",
      segments:[{plain:"A Milky Way object that "},{choice:"A",text:"erupted"},{plain:" in the constellation Scorpius has "},{choice:"B",text:"provides"},{plain:" information to "},{choice:"C",text:"astronomers"},{plain:" since "},{choice:"D",text:"July"},{plain:"."}] },
    { type:"err", _skill:20, answer:"A", correction:"'Much' → 'Many' (fossils sayılabilir)",
      explain:"Skill 20: 'fossils' sayılabilir çoğul → 'Many'.",
      segments:[{choice:"A",text:"Much"},{plain:" "},{choice:"B",text:"fossils"},{plain:" are "},{choice:"C",text:"found"},{plain:" in coal-bearing "},{choice:"D",text:"rocks"},{plain:"."}] },
    { type:"err", _skill:25, answer:"C", correction:"'coldly' → 'cold' (linking verb 'becomes' + sıfat)",
      explain:"Skill 25: linking verb sonrası sıfat → 'cold'.",
      segments:[{plain:"When salt is "},{choice:"A",text:"added"},{plain:" to ice, this mixture "},{choice:"B",text:"becomes"},{plain:" "},{choice:"C",text:"coldly"},{plain:" enough to freeze ice "},{choice:"D",text:"cream"},{plain:"."}] },
    { type:"err", _skill:14, answer:"C", correction:"'build' → 'building' (paralellik: fishing, whaling, building)",
      explain:"Skill 14: liste paralel olmalı → 'building'.",
      segments:[{plain:"Long Island was chiefly an "},{choice:"A",text:"agricultural"},{plain:" region with "},{choice:"B",text:"fishing"},{plain:", whaling, and "},{choice:"C",text:"build"},{plain:" ships as the important "},{choice:"D",text:"industries"},{plain:"."}] },
    { type:"err", _skill:13, answer:"B", correction:"'know' → 'knows' ('No one' tekil)",
      explain:"Skill 13: 'No one' tekildir → 'knows'.",
      segments:[{plain:"No one who has "},{choice:"A",text:"studied"},{plain:" the Battle of Little Bighorn "},{choice:"B",text:"know"},{plain:" the exact "},{choice:"C",text:"route"},{plain:" that Custer and his detachment "},{choice:"D",text:"took"},{plain:"."}] },
    { type:"err", _skill:17, answer:"D", correction:"'discover' → 'discovered' (been + V3)",
      explain:"Skill 17: 'have been' + past participle → 'discovered'.",
      segments:[{plain:"In the solar system, billions of "},{choice:"A",text:"meteorites"},{plain:" "},{choice:"B",text:"have"},{plain:" so far "},{choice:"C",text:"been"},{plain:" "},{choice:"D",text:"discover"},{plain:"."}] },
    { type:"err", _skill:23, answer:"C", correction:"'his' → 'their' ('families' çoğul)",
      explain:"Skill 23: zamir 'families' (çoğul) ile uyumlu → 'their'.",
      segments:[{plain:"Many of America's "},{choice:"A",text:"super-rich"},{plain:" families "},{choice:"B",text:"made"},{plain:" Newport "},{choice:"C",text:"his"},{plain:" favorite summer "},{choice:"D",text:"resort"},{plain:"."}] },
    { type:"err", _skill:6, answer:"B", correction:"'is' → 'it is' (clause'un öznesi eksik)",
      explain:"Skill 6: 'because' clause'unun öznesi yok → 'it is'.",
      segments:[{plain:"Mars "},{choice:"A",text:"looks"},{plain:" red because "},{choice:"B",text:"is"},{plain:" "},{choice:"C",text:"covered"},{plain:" with a layer of soft red iron "},{choice:"D",text:"oxide"},{plain:"."}] },
    { type:"err", _skill:15, answer:"C", correction:"'or' → 'nor' (neither … nor)",
      explain:"Skill 15: 'neither … nor' kalıbı.",
      segments:[{plain:"The radioactive "},{choice:"A",text:"substances"},{plain:" that pose the greatest harm to humanity have "},{choice:"B",text:"neither"},{plain:" very short "},{choice:"C",text:"or"},{plain:" very long "},{choice:"D",text:"half lives"},{plain:"."}] },
    { type:"err", _skill:19, answer:"C", correction:"'eyes' → 'eye' ('one' tekil ister)",
      explain:"Skill 19: 'one' tekil isim alır → 'eye'.",
      segments:[{plain:"A robin "},{choice:"A",text:"cocks"},{plain:" its head to "},{choice:"B",text:"peer at"},{plain:" a worm with one "},{choice:"C",text:"eyes"},{plain:" and not to "},{choice:"D",text:"hear"},{plain:" it."}] },
    { type:"err", _skill:9, answer:"C", correction:"'who' → 'which' (insan değil, sistem)",
      explain:"Skill 9: insan olmayan için 'which'.",
      segments:[{plain:"Film sound is often "},{choice:"A",text:"recorded"},{plain:" by an "},{choice:"B",text:"analog"},{plain:" system "},{choice:"C",text:"who"},{plain:" uses "},{choice:"D",text:"light"},{plain:"."}] },
    { type:"err", _skill:24, answer:"C", correction:"'high' → 'highly' (sıfatı niteler, zarf)",
      explain:"Skill 24: 'decorated' sıfatını niteleyen zarf → 'highly'.",
      segments:[{plain:"The "},{choice:"A",text:"scribes"},{plain:" of the Middle Ages used quill pens to "},{choice:"B",text:"produce"},{plain:" their "},{choice:"C",text:"high"},{plain:" decorated "},{choice:"D",text:"manuscripts"},{plain:"."}] },
    { type:"err", _skill:11, answer:"C", correction:"'has' → 'have' (özne 'principles' çoğul)",
      explain:"Skill 11: asıl özne 'principles' (çoğul); araya uzun öbek girmiş.",
      segments:[{plain:"The "},{choice:"A",text:"principles"},{plain:" of physics "},{choice:"B",text:"described"},{plain:" by Christian Doppler in 1842 "},{choice:"C",text:"has"},{plain:" been "},{choice:"D",text:"adapted"},{plain:" to evaluate the movement of blood."}] },
    { type:"err", _skill:22, answer:"C", correction:"'ours' → 'our' (ismin önünde iyelik sıfatı)",
      explain:"Skill 22: isimden önce iyelik sıfatı → 'our'.",
      segments:[{plain:"The Pioneer 10 and 11 spacecraft were the "},{choice:"A",text:"first"},{plain:" vehicles of humankind to "},{choice:"B",text:"venture"},{plain:" beyond the limits of "},{choice:"C",text:"ours"},{plain:" "},{choice:"D",text:"solar system"},{plain:"."}] }
  ]
};
if (typeof module!=="undefined") module.exports = { BOOK };
