/* ==========================================================================
   TOEFL Kelime Çalışması — akademik kelime listesi
   Her madde: { w: kelime, pos: tür, tr: Türkçe anlam, ex: örnek cümle }
   Flashcard + çoktan seçmeli quiz için kullanılır.
   ========================================================================== */
const VOCAB = [
  {w:"abundant", pos:"adj", tr:"bol, çok miktarda", ex:"Water is abundant in this region."},
  {w:"accelerate", pos:"v", tr:"hızlandırmak", ex:"The plan will accelerate economic growth."},
  {w:"accurate", pos:"adj", tr:"doğru, kesin", ex:"The measurements must be accurate."},
  {w:"acquire", pos:"v", tr:"edinmek, elde etmek", ex:"She acquired new skills quickly."},
  {w:"adequate", pos:"adj", tr:"yeterli", ex:"The funding was adequate for the project."},
  {w:"adjacent", pos:"adj", tr:"bitişik, komşu", ex:"The lab is adjacent to the library."},
  {w:"advocate", pos:"v/n", tr:"savunmak; savunucu", ex:"They advocate for cleaner energy."},
  {w:"aggregate", pos:"n/adj", tr:"toplam, küme", ex:"The aggregate score determines the rank."},
  {w:"allocate", pos:"v", tr:"tahsis etmek, ayırmak", ex:"The budget was allocated to research."},
  {w:"ambiguous", pos:"adj", tr:"belirsiz, çift anlamlı", ex:"The instructions were ambiguous."},
  {w:"analyze", pos:"v", tr:"çözümlemek, analiz etmek", ex:"Scientists analyze the data carefully."},
  {w:"anticipate", pos:"v", tr:"öngörmek, beklemek", ex:"We anticipate strong demand."},
  {w:"apparent", pos:"adj", tr:"açık, görünen", ex:"The cause was not immediately apparent."},
  {w:"arbitrary", pos:"adj", tr:"keyfi, rastgele", ex:"The decision seemed arbitrary."},
  {w:"assess", pos:"v", tr:"değerlendirmek", ex:"Teachers assess student progress."},
  {w:"assumption", pos:"n", tr:"varsayım", ex:"The theory rests on a key assumption."},
  {w:"attain", pos:"v", tr:"ulaşmak, elde etmek", ex:"He attained his goals through effort."},
  {w:"attribute", pos:"v/n", tr:"atfetmek; özellik", ex:"They attribute the success to teamwork."},
  {w:"benefit", pos:"n/v", tr:"yarar; yararlanmak", ex:"Exercise benefits your health."},
  {w:"bias", pos:"n", tr:"önyargı, yanlılık", ex:"The study tried to avoid bias."},
  {w:"coherent", pos:"adj", tr:"tutarlı, anlaşılır", ex:"She gave a coherent explanation."},
  {w:"coincide", pos:"v", tr:"aynı zamana denk gelmek", ex:"The events coincided exactly."},
  {w:"collapse", pos:"v/n", tr:"çökmek; çöküş", ex:"The old bridge collapsed."},
  {w:"comprehensive", pos:"adj", tr:"kapsamlı", ex:"A comprehensive report was published."},
  {w:"comprise", pos:"v", tr:"oluşmak, içermek", ex:"The team comprises ten members."},
  {w:"conceive", pos:"v", tr:"tasarlamak, akıl etmek", ex:"He conceived a new approach."},
  {w:"consequence", pos:"n", tr:"sonuç", ex:"Every action has consequences."},
  {w:"considerable", pos:"adj", tr:"hatırı sayılır, önemli", ex:"They made considerable progress."},
  {w:"constitute", pos:"v", tr:"oluşturmak", ex:"Women constitute half the workforce."},
  {w:"contradict", pos:"v", tr:"çelişmek, yalanlamak", ex:"The results contradict the theory."},
  {w:"contribute", pos:"v", tr:"katkıda bulunmak", ex:"Many factors contribute to climate change."},
  {w:"controversial", pos:"adj", tr:"tartışmalı", ex:"It is a controversial topic."},
  {w:"convey", pos:"v", tr:"iletmek, aktarmak", ex:"Words convey meaning."},
  {w:"crucial", pos:"adj", tr:"çok önemli, kritik", ex:"Timing is crucial in this experiment."},
  {w:"cumulative", pos:"adj", tr:"birikimli", ex:"The effect is cumulative over time."},
  {w:"decline", pos:"v/n", tr:"azalmak; düşüş", ex:"Sales declined last year."},
  {w:"deduce", pos:"v", tr:"çıkarsamak", ex:"We can deduce the answer from the data."},
  {w:"deficient", pos:"adj", tr:"eksik, yetersiz", ex:"The diet was deficient in vitamins."},
  {w:"demonstrate", pos:"v", tr:"göstermek, kanıtlamak", ex:"The study demonstrates a clear link."},
  {w:"denote", pos:"v", tr:"belirtmek, göstermek", ex:"This symbol denotes danger."},
  {w:"deplete", pos:"v", tr:"tüketmek, azaltmak", ex:"Overuse depletes natural resources."},
  {w:"derive", pos:"v", tr:"türetmek, elde etmek", ex:"The word derives from Latin."},
  {w:"deteriorate", pos:"v", tr:"kötüleşmek, bozulmak", ex:"His health deteriorated rapidly."},
  {w:"diminish", pos:"v", tr:"azalmak, küçülmek", ex:"Interest diminished over time."},
  {w:"distinct", pos:"adj", tr:"farklı, belirgin", ex:"There are three distinct phases."},
  {w:"diverse", pos:"adj", tr:"çeşitli", ex:"The city has a diverse population."},
  {w:"dominant", pos:"adj", tr:"baskın, egemen", ex:"The dominant species thrives here."},
  {w:"elaborate", pos:"adj/v", tr:"ayrıntılı; detaylandırmak", ex:"She gave an elaborate description."},
  {w:"eliminate", pos:"v", tr:"ortadan kaldırmak", ex:"The new method eliminates errors."},
  {w:"emerge", pos:"v", tr:"ortaya çıkmak", ex:"New evidence emerged later."},
  {w:"emphasize", pos:"v", tr:"vurgulamak", ex:"The teacher emphasized accuracy."},
  {w:"endure", pos:"v", tr:"dayanmak, katlanmak", ex:"The structure endured the storm."},
  {w:"enhance", pos:"v", tr:"geliştirmek, artırmak", ex:"Training enhances performance."},
  {w:"enormous", pos:"adj", tr:"devasa, çok büyük", ex:"The project required enormous effort."},
  {w:"equivalent", pos:"adj/n", tr:"eşdeğer", ex:"One mile is equivalent to 1.6 km."},
  {w:"essential", pos:"adj", tr:"temel, gerekli", ex:"Water is essential for life."},
  {w:"evident", pos:"adj", tr:"açık, belli", ex:"It was evident that he was tired."},
  {w:"evolve", pos:"v", tr:"evrilmek, gelişmek", ex:"Species evolve over generations."},
  {w:"exceed", pos:"v", tr:"aşmak, geçmek", ex:"Costs exceeded the budget."},
  {w:"exhibit", pos:"v/n", tr:"sergilemek; sergi", ex:"The samples exhibit unusual properties."},
  {w:"explicit", pos:"adj", tr:"açık, belirgin", ex:"The rules are explicit."},
  {w:"facilitate", pos:"v", tr:"kolaylaştırmak", ex:"Technology facilitates learning."},
  {w:"feasible", pos:"adj", tr:"uygulanabilir, olası", ex:"The plan is technically feasible."},
  {w:"fluctuate", pos:"v", tr:"dalgalanmak", ex:"Prices fluctuate with demand."},
  {w:"fundamental", pos:"adj", tr:"temel", ex:"This is a fundamental principle."},
  {w:"generate", pos:"v", tr:"üretmek, oluşturmak", ex:"The dam generates electricity."},
  {w:"hypothesis", pos:"n", tr:"hipotez, varsayım", ex:"They tested the hypothesis."},
  {w:"implement", pos:"v", tr:"uygulamak, hayata geçirmek", ex:"The school implemented a new policy."},
  {w:"implication", pos:"n", tr:"sonuç, ima", ex:"The findings have wide implications."},
  {w:"incentive", pos:"n", tr:"teşvik", ex:"Tax breaks are an incentive to invest."},
  {w:"inevitable", pos:"adj", tr:"kaçınılmaz", ex:"Change is inevitable."},
  {w:"infer", pos:"v", tr:"çıkarım yapmak", ex:"We infer meaning from context."},
  {w:"inherent", pos:"adj", tr:"doğasında olan, içkin", ex:"Risk is inherent in investing."},
  {w:"initiate", pos:"v", tr:"başlatmak", ex:"They initiated a new program."},
  {w:"innovative", pos:"adj", tr:"yenilikçi", ex:"The design is highly innovative."},
  {w:"integrate", pos:"v", tr:"bütünleştirmek", ex:"The app integrates several tools."},
  {w:"intricate", pos:"adj", tr:"karmaşık, ince işli", ex:"The machine has an intricate design."},
  {w:"intrinsic", pos:"adj", tr:"özünde olan", ex:"Curiosity has intrinsic value."},
  {w:"justify", pos:"v", tr:"haklı çıkarmak", ex:"He could not justify the cost."},
  {w:"magnitude", pos:"n", tr:"büyüklük, çap", ex:"The magnitude of the problem was clear."},
  {w:"manipulate", pos:"v", tr:"işlemek, yönlendirmek", ex:"Scientists manipulate variables."},
  {w:"negligible", pos:"adj", tr:"önemsiz, ihmal edilebilir", ex:"The difference was negligible."},
  {w:"notion", pos:"n", tr:"fikir, kavram", ex:"The notion is widely accepted."},
  {w:"obscure", pos:"adj/v", tr:"belirsiz; gizlemek", ex:"The meaning remained obscure."},
  {w:"obtain", pos:"v", tr:"elde etmek", ex:"They obtained permission first."},
  {w:"overlap", pos:"v/n", tr:"örtüşmek; örtüşme", ex:"The two fields overlap considerably."},
  {w:"persist", pos:"v", tr:"sürmek, ısrar etmek", ex:"The problem persisted for years."},
  {w:"phenomenon", pos:"n", tr:"olgu, fenomen", ex:"It is a natural phenomenon."},
  {w:"plausible", pos:"adj", tr:"akla yatkın, makul", ex:"That is a plausible explanation."},
  {w:"precise", pos:"adj", tr:"kesin, tam", ex:"We need precise measurements."},
  {w:"predominant", pos:"adj", tr:"baskın, ağır basan", ex:"The predominant color is blue."},
  {w:"presume", pos:"v", tr:"varsaymak", ex:"I presume you have read the report."},
  {w:"prevail", pos:"v", tr:"hüküm sürmek, galip gelmek", ex:"Calm prevailed after the storm."},
  {w:"profound", pos:"adj", tr:"derin, köklü", ex:"The discovery had a profound impact."},
  {w:"prohibit", pos:"v", tr:"yasaklamak", ex:"The law prohibits smoking here."},
  {w:"prominent", pos:"adj", tr:"önde gelen, göze çarpan", ex:"She is a prominent scientist."},
  {w:"prone", pos:"adj", tr:"eğilimli, yatkın", ex:"The area is prone to flooding."},
  {w:"refute", pos:"v", tr:"çürütmek, yalanlamak", ex:"New data refuted the claim."},
  {w:"reinforce", pos:"v", tr:"pekiştirmek, güçlendirmek", ex:"Practice reinforces learning."},
  {w:"reluctant", pos:"adj", tr:"isteksiz, gönülsüz", ex:"He was reluctant to agree."},
  {w:"resemble", pos:"v", tr:"benzemek", ex:"The copy resembles the original."},
  {w:"reside", pos:"v", tr:"ikamet etmek, bulunmak", ex:"Many species reside in the forest."},
  {w:"retain", pos:"v", tr:"korumak, akılda tutmak", ex:"The soil retains moisture."},
  {w:"rigorous", pos:"adj", tr:"titiz, sıkı", ex:"The test was rigorous."},
  {w:"scarce", pos:"adj", tr:"kıt, az bulunur", ex:"Fresh water is scarce here."},
  {w:"significant", pos:"adj", tr:"önemli, anlamlı", ex:"There was a significant increase."},
  {w:"simultaneous", pos:"adj", tr:"eşzamanlı", ex:"The events were simultaneous."},
  {w:"sophisticated", pos:"adj", tr:"gelişmiş, sofistike", ex:"They use sophisticated equipment."},
  {w:"subsequent", pos:"adj", tr:"sonraki, takip eden", ex:"Subsequent tests confirmed it."},
  {w:"substantial", pos:"adj", tr:"önemli, hatırı sayılır", ex:"A substantial amount was raised."},
  {w:"sufficient", pos:"adj", tr:"yeterli", ex:"There was sufficient evidence."},
  {w:"suppress", pos:"v", tr:"bastırmak", ex:"The drug suppresses symptoms."},
  {w:"sustain", pos:"v", tr:"sürdürmek, ayakta tutmak", ex:"The economy sustained growth."},
  {w:"tentative", pos:"adj", tr:"geçici, kesin olmayan", ex:"They reached a tentative agreement."},
  {w:"terminate", pos:"v", tr:"sonlandırmak", ex:"The contract was terminated."},
  {w:"thrive", pos:"v", tr:"gelişmek, serpilmek", ex:"Plants thrive in sunlight."},
  {w:"transmit", pos:"v", tr:"iletmek, bulaştırmak", ex:"Nerves transmit signals."},
  {w:"undergo", pos:"v", tr:"geçirmek, maruz kalmak", ex:"The material undergoes change."},
  {w:"undermine", pos:"v", tr:"baltalamak, zayıflatmak", ex:"Errors undermine trust."},
  {w:"uniform", pos:"adj", tr:"tek tip, aynı", ex:"The quality is uniform."},
  {w:"utilize", pos:"v", tr:"kullanmak, yararlanmak", ex:"They utilize solar energy."},
  {w:"valid", pos:"adj", tr:"geçerli", ex:"That is a valid argument."},
  {w:"vary", pos:"v", tr:"değişmek, farklılık göstermek", ex:"Prices vary by region."},
  {w:"versatile", pos:"adj", tr:"çok yönlü", ex:"It is a versatile tool."},
  {w:"viable", pos:"adj", tr:"yaşayabilir, uygulanabilir", ex:"They found a viable solution."},
  {w:"vital", pos:"adj", tr:"hayati, çok önemli", ex:"Sleep is vital for health."},
  {w:"widespread", pos:"adj", tr:"yaygın", ex:"The practice is widespread."},
  {w:"yield", pos:"v/n", tr:"vermek, ürün; verim", ex:"The experiment yielded results."}
];
if (typeof module!=="undefined") module.exports = { VOCAB };
